package e

const (
	SUCCESS        = 200
	ERROR          = 500
	INVALID_PARAMS = 400

	ERROR_EXIST_TAG = iota + 998
	ERROR_NOT_EXIST_TAG
	ERROR_NOT_EXIST_ARTICLE

	ERROR_AUTH_CHECK_TOKEN_FAIL = iota + 1995
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT
	ERROR_AUTH_TOKEN
	ERROR_AUTH

	// 保存图片失败
	ERROR_UPLOAD_SAVE_IMAGE_FAIL = iota + 29991
	// 检查图片失败
	ERROR_UPLOAD_CHECK_IMAGE_FAIL
	// 校验图片错误，图片格式或大小有问题
	ERROR_UPLOAD_CHECK_IMAGE_FORMAT

	ERROR_CHECK_EXIST_ARTICLE_FAIL = iota + 3988
	ERROR_GET_ARTICLE_FAIL
)
